apiVersion: v2
name: bitwarden-directory-connector
description: |
  This Helm Chart installs the Bitwarden Directory Connector as a
  CronJob on a Kubernetes cluster.  It uses the `estenrye/bwdc`
  docker image.

  Related Links
    - [About Bitwarden Directory Connector](https://bitwarden.com/help/directory-sync/)
    - [Bitwarden Directory Connector CLI Documentation](https://bitwarden.com/help/directory-sync-cli/)
    - [Bitwarden Directory Connector GitHub Repository](https://github.com/bitwarden/directory-connector)
    - [estenrye/bwdc Docker Image GitHub Repository](https://github.com/estenrye/docker-bwdc)

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v0.0.20"
