apiVersion: v2
name: bitwarden-directory-connector
description: |
  This Helm Chart installs the Bitwarden Directory Connector as a
  CronJob on a Kubernetes cluster.  It uses the `estenrye/bwdc`
  docker image.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.6

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v0.0.20"

home: https://github.com/estenrye/helm-charts

sources:
  - https://github.com/estenrye/helm-charts/tree/main/charts/bitwarden-directory-connector
  - https://github.com/estenrye/docker-bwdc

maintainers:
  - name: Esten Rye
    url: https://github.com/estenrye

annotations:
  artifacthub.io/images: |
    - name: bwdc
      image: estenrye/bwdc:v0.0.20
  artifacthub.io/links: |
    - name: About Bitwarden Directory Connector
      url: https://bitwarden.com/help/directory-sync/
    - name: Bitwarden Directory Connector CLI Documentation
      url: https://bitwarden.com/help/directory-sync-cli/
    - name: Bitwarden Directory Connector GitHub Repository
      url: https://github.com/bitwarden/directory-connector
    - name: estenrye/bwdc Docker Image GitHub Repository
      url: https://github.com/estenrye/docker-bwdc
  artifacthub.io/operator: "false"
