# Default values for bitwarden-directory-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # -- Docker Image Repository Name.
  repository: estenrye/bwdc

  # -- (string) Overrides the image tag whose default is the chart appVersion.
  tag:

  # -- Configures the image pull policy.  Valid options include
  # [`Always`, `IfNotPresent`, `Never`]
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

bitwarden:
  organization:
    # -- The Bitwarden API Client Id for the Organization.
    # You must replace the value in this field.  You can find this by navigating
    # to your Bitwarden Organization Settings and clicking View API Key.
    client-id: "organization.b5351047-89b6-820f-ad21016b6222"

    # -- The Bitwarden API Client Secret for the Organization.
    # You must replace the value in this field.  You can find this by navigating
    # to your Bitwarden Organization Settings and clicking View API Key.
    client-secret: "yUMB4trbqV1bavhEHGqbuGpz4AlHm9"