apiVersion: v2
name: vscode-server
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.4.10

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "4.4.0"

home: https://github.com/estenrye/helm-charts

dependencies:
  - name: step-certificates
    repository: https://smallstep.github.io/helm-charts/
    version: 1.18.2+20220324
  - name: step-issuer
    repository: https://smallstep.github.io/helm-charts/
    version: 0.6.4
    tags:
      - install-step-issuer
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.8.0
    tags:
      - install-cert-manager

sources:
  - https://github.com/estenrye/helm-charts/tree/main/charts/vscode-server
  - https://github.com/cdr/code-server
  - https://github.com/linuxserver/docker-code-server

maintainers:
  - name: Esten Rye
    url: https://github.com/estenrye

annotations:
  artifacthub.io/images: |
    - name: linuxserver/code-server
      image: linuxserver/code-server:4.4.0
    - name: library/docker
      image: library/docker:dind-rootless
  artifacthub.io/links: |
    - name: code-server Documentation
      url: https://github.com/cdr/code-server/blob/v3.5.0/doc/guide.md
    - name: LinuxServer.io Fleet - linuxserver/code-server
      url: https://fleet.linuxserver.io/image?name=linuxserver/code-server
    - name: How To Set Up the code-server Cloud IDE Platform on DigitalOcean Kubernetes
      url: https://www.digitalocean.com/community/tutorials/how-to-set-up-the-code-server-cloud-ide-platform-on-digitalocean-kubernetes
  artifacthub.io/operator: "false"
