# Default values for vscode-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

password:
  # -- When true, enables creation of secret containing the code
  # server password and mapping of that secret to the PASSWORD
  # environment variable.
  enabled: false

  # -- Value of the password to set and map to the PASSWORD
  # environment variable.
  value: ""

# -- Number of replicas to provision.
replicaCount: 1

image:
  # -- Docker Image Repository Name.
  repository: linuxserver/code-server

  # -- Configures the image pull policy.  Valid options include
  # [`Always`, `IfNotPresent`, `Never`]
  pullPolicy: IfNotPresent
  
  # -- (string) Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- image pull secrets to retrieve image if required.
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- map of annotations to apply to the pod.
podAnnotations: {}

# -- map of pod security context settings to apply to the pod.
podSecurityContext: {}
  # fsGroup: 2000

# -- map of security context settings to apply to the pod.
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- specifies the Kubernetes Service type to create.
  type: ClusterIP
  # -- port the service should receive traffic on.
  port: 80
  # -- port the service should sent traffic to.
  containerPort: 8443

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
  hosts:
    - host: code-server.cluster.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
    # - hosts:
    #     - code-server.cluster.local
    #   secretName: code-server-tls

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  annotations: {}
  accessModes:
    - ReadWriteOnce
  dataSource: {}
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""