apiVersion: v2
name: fluentd-aws-cloudtrail-processor
description: |
  This Helm Chart installs FluentD and connects it to an AWS SQS Queue
  and AWS S3 Bucket to consume AWS Cloudtrail logs and Push them to an
  EFK Instance.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "latest"

home: https://github.com/estenrye/helm-charts

sources:
  - https://github.com/estenrye/helm-charts/tree/main/charts/fluentd-aws-cloudtrail-processor
  - https://github.com/estenrye/slides/docker/estenrye/fluentd-cloudtrail

maintainers:
  - name: Esten Rye
    url: https://github.com/estenrye

annotations:
  artifacthub.io/images: |
    - name: estenrye/fluentd-cloudtrail
      image: docker.io/estenrye/fluentd-cloudtrail:latest
  artifacthub.io/links: |
    - name: FluentD S3 Plugin GitHub
      url: https://github.com/fluent/fluent-plugin-s3
    - name: estenrye/fluentd-cloudtrail Docker Image GitHub Repository
      url: https://github.com/estenrye/slides/docker/estenrye/fluentd-cloudtrail
  artifacthub.io/operator: "false"
