apiVersion: v1
data:
  cluster_name: {{ .Values.cluster_name | default .Release.Name }}
  top_level_domain:  {{ .Values.top_level_domain }}
  dns_suffix: services.{{ .Values.cluster_name | default .Release.Name }}.{{ .Values.top_level_domain }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cluster-base-config
  labels:
    {{- include "cluster_base_config.labels" . | nindent 4 }}