apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vscode-server.fullname" . }}-binding
  labels:
    {{- include "vscode-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ include "vscode-server.serviceAccountName" . }}
  namespace: {{ Release.Namespace }}