apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vscode-server.fullname" . }}
  labels:
    {{- include "vscode-server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vscode-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vscode-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vscode-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: code-server
          securityContext:
            {{- toYaml .Values.vscode_server.securityContext | nindent 12 }}
          image: "{{ .Values.vscode_server.image.repository }}:{{ .Values.vscode_server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.vscode_server.image.pullPolicy }}
          env:
            - name: DOCKER_HOST
              value: tcp://0.0.0.0:2376
            - name: DOCKER_TLS_VERIFY
              value: '1'
            - name: DOCKER_CONFIG
              value: /config/.docker
            - name: DOCKER_CERT_PATH
              value: /docker-tls-certs/client
          {{- if .Values.vscode_server.password.enabled }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vscode-server.fullname" . }}-password
                  key: password
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.vscode_server.service.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.vscode_server.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /docker-tls-certs
              name: docker-tls-certs
              readOnly: true
          {{- if .Values.vscode_server.persistence.enabled }}
            - mountPath: /config
              name: config
          {{- end }}
        - name: dind-daemon
          securityContext:
            {{- toYaml .Values.docker_daemon.securityContext | nindent 12 }}
          image: "{{ .Values.docker_daemon.image.repository }}:{{ .Values.docker_daemon.image.tag }}"
          imagePullPolicy: {{ .Values.docker_daemon.image.pullPolicy }}
          env:
            - name: DOCKER_TLS_CERTDIR
              value: /docker-tls-certs
          ports:
            - name: dind-tls
              containerPort: 2376
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.docker_daemon.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /docker-tls-certs
              name: docker-tls-certs
              readOnly: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: docker-tls-certs
          secret:
            secretName: {{ include "vscode-server.fullname" . }}-docker-tls
            defaultMode: 0664
      {{- if .Values.vscode_server.persistence.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "vscode-server.fullname" . }}-config
      {{- end }}
