apiVersion: certmanager.step.sm/v1beta1
kind: StepIssuer
metadata:
  name: {{ .Release.Name }}-step-issuer
spec:
  # The CA URL.
  url: https://{{ .Release.Name }}-step-certificates.{{ .Release.Namespace }}.svc.cluster.local
  # The base64 encoded version of the CA root certificate in PEM format.
  caBundle:  {{ index .Values "step-certificates" "inject" "certificates" "root_ca" | b64enc }}
  # The provisioner name, kid, and a reference to the provisioner password secret.
  provisioner:
    name: {{ index .Values "step-certificates" "inject" "config" "files" "ca.json" "authority" "provisioners" 0 "name" }}
    kid: {{ index .Values "step-certificates" "inject" "config" "files" "ca.json" "authority" "provisioners" 0 "key" "kid" }}
    passwordRef:
      name: {{ .Release.Name }}-step-certificates-provisioner-password
      key: password