{{- if .Values.vscode_server.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vscode-server.fullname" . }}-config
  labels:
    {{- include "vscode-server.labels" . | nindent 4 }}
  {{- with .Values.vscode_server.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.vscode_server.persistence.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.vscode_server.persistence.dataSource }}
  dataSource:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.vscode_server.persistence.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.vscode_server.persistence.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  storageClassName: {{ .Values.vscode_server.persistence.storageClassName }}
  {{- if .Values.vscode_server.persistence.volumeMode }}
  volumeMode: {{ .Values.vscode_server.persistence.volumeMode }}
  {{- end }}
  {{- if .Values.vscode_server.persistence.volumeName }}
  volumneName: {{ .Values.vscode_server.persistence.volumeName }}
  {{- end }}
{{- end }}