{{- if .Values.vscode_server.password.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vscode-server.fullname" . }}-password
  labels:
    {{- include "vscode-server.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.vscode_server.password.value }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vscode-server.fullname" . }}-docker-tls
  labels:
    {{- include "vscode-server.labels" . | nindent 4 }}
type: Opaque
data:
  ca:
    cert.pem:
    key.pem:
  server:
    ca.pem:
    cert.pem:
    key.pem:
  client:
    ca.pem:
    cert.pem:
    key.pem: