{{- if .Values.password.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vscode-server.fullname" . }}-password
  labels:
    {{- include "vscode-server.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.password.value }}
{{- end }}