{{- if .Values.vscode_server.password.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vscode-server.fullname" . }}-password
  labels:
    {{- include "vscode-server.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.vscode_server.password.value }}
{{- end }}
{{- if .Values.vscode_server.ssh-key.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vscode-server.fullname" . }}-ssh-key
data:
  id_rsa: {{ .Values.vscode_server.ssh-key.id_rsa.key }}
  id_rsa.pub: {{ .Values.vscode_server.ssh-key.id_rsa.pub }}
{{- end }}