---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentd-aws-cloudtrail-processor.fullname" . }}-fluent-conf
  labels:
    {{- include "fluentd-aws-cloudtrail-processor.labels" . | nindent 4 }}
data:
  fluent.conf: |
    # Include config files in fluent.conf.d directory
    @include fluent.conf.d/*.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentd-aws-cloudtrail-processor.fullname" . }}-fluent-conf-d
  labels:
    {{- include "fluentd-aws-cloudtrail-processor.labels" . | nindent 4 }}
data:
  aws-cloudtrail-source.conf: |
    <source>
      @type s3
      tag aws-cloudtrail-raw
      
      <shared_credentials>
        path /fluentd/aws/credentials
        profile_name default
      </shared_credentials>

      s3_bucket {{ .Values.fluentd.s3_bucket }}
      s3_region {{ .Values.fluentd.aws_region }}

      add_object_metadata true
      store_as gzip

      <sqs>
        queue_name {{ .Values.fluentd.sqs_queue_name }}
        skip_delete {{ .Values.fluentd.sqs_skip_delete }}
        wait_time_seconds {{ .Values.fluentd.sqs_wait_time_seconds }}
        retry_error_interval {{ .Values.fluentd.sqs_retry_error_interval }}
      </sqs>
      <parse>
        @type json
      </parse>
    </source>
  aws-cloudtrail-match.conf: |
{{- if .Values.fluentd.enable_elasticsearch }}
    <match aws-cloudtrail-records>
      @type elasticsearch
      scheme {{ .Values.fluentd.elasticsearch_scheme }}
      host {{ .Values.fluentd.elasticsearch_host }}
      path {{ .Values.fluentd.elasticsearch_path }}
      port {{ .Values.fluentd.elasticsearch_port }}
      user {{ .Values.fluentd.elasticsearch_username }}
      password {{ .Values.fluentd.elasticsearch_password }}
      logstash_format true
      logstash_prefix {{ .Values.fluentd.elasticsearch_logstash_prefix }}
    </match>
{{- end }}
{{- if .Values.fluentd.enable_stdout_raw }}
    <filter aws-cloudtrail-raw>
      @type stdout
      output_type json
    </filter>
{{- end }}
{{- if .Values.fluentd.enable_stdout }}
    <match aws-cloudtrail-records>
      @type stdout
      output_type json
    </match>
{{- end }}
  aws-cloudtrail-filter.conf: |
    <match aws-cloudtrail-raw>
      type record_splitter
      tag aws-cloudtrail-records
      split_key Records
      keep_keys ["s3_bucket","s3_key"]
    </match>
