apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fluentd-aws-cloudtrail-processor.fullname" . }}
  labels:
    {{- include "fluentd-aws-cloudtrail-processor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fluentd-aws-cloudtrail-processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fluentd-aws-cloudtrail-processor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      serviceAccountName: {{ include "fluentd-aws-cloudtrail-processor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /fluentd/aws
              name: aws-credentials
              readOnly: true
            - mountPath: /fluentd/etc
              name: fluent-conf
              readOnly: true
            - mountPath: /fluentd/etc/fluent.conf.d
              name: fluent-conf-d
              readOnly: true
      volumes:
        - name: aws-credentials
          secret:
            secretName: {{ include "fluentd-aws-cloudtrail-processor.fullname" . }}-aws-shared-creds
        - name: fluent-conf
          configMap:
            name: {{ include "fluentd-aws-cloudtrail-processor.fullname" . }}-fluent-conf
        - name: fluent-conf-d
          configMap:
            name: {{ include "fluentd-aws-cloudtrail-processor.fullname" . }}-fluent-conf-d
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
