---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluentd-aws-cloudtrail-processor.fullname" . }}-aws-shared-creds
  labels:
    {{- include "fluentd-aws-cloudtrail-processor.labels" . | nindent 4 }}
type: Opaque
data:
  credentials: {{ include "fluentd-aws-cloudtrail-processor.aws-credentials" . | b64enc }}