apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "cert-manager-install.fullname" . }}
  labels:
    {{- include "cert-manager-install.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.acme_email }}
    server: {{ .Values.acme_server }}
    privateKeySecretRef:
      name: cloudflare-cluster-issuer-private-key-secret
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{ include "cert-manager-install.fullname" . }}-cloudflare
              key: api-token