apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-manager-install.fullname" . }}-cloudflare
  labels:
    {{- include "cert-manager-install.labels" . | nindent 4 }}
type: Opaque
data:
  api-token: {{ .Values.cloudflare_api_token | b64enc }}
