---
name: chart-publish
on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
  workflow_dispatch:
    branches:
      - main

permissions: read-all

jobs:
  publish:
    permissions:
      contents: write # for helm/chart-releaser-action to push chart release and create a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@217bf70cbd2e930ba2e81ba7e1de2f7faecc42ba # tag=v2.1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get helm-docs-version
        uses: sergeysova/jq-action@v2
        id: brewfile_helm_docs_version
        with:
          cmd: 'jq ".entries.brew[\"helm-docs\"].version" -r Brewfile.lock.json'
        
      - name: install helm-docs
        run: |
          cd /tmp
          wget https://github.com/norwoodj/helm-docs/releases/download/v${{ steps.brewfile_helm_docs_version.outputs.value }}/helm-docs_${{  steps.brewfile_helm_docs_version.outputs.value }}_Linux_x86_64.tar.gz
          tar -xvf helm-docs_${{ steps.brewfile_helm_docs_version.outputs.value }}_Linux_x86_64.tar.gz
          sudo mv helm-docs /usr/local/sbin
      - name: list chart directories
        id: chart_dirs
        run: |
          echo "::set-output name=charts::$(find charts -type d -maxdepth 1 -mindepth 1)"
      - name: echo chart_dirs
        run:
          echo "${{ steps.chart_dirs.outputs.charts }}"
      - name: run helm-docs
        run: |
          helm-docs \
            --chart-search-root=charts \
            --template-files=./_chart_README.md.title.gotmpl \
            --template-files=README.md.badges.gotmpl \
            --template-files=./_chart_README.md.body.gotmpl \
            --template-files=README.md.legalgotmpl

      - name: Run Artifact Hub lint
        run: |
          CHARTS="${{ steps.chart_dirs.outputs.charts }}"
          curl -s https://api.github.com/repos/artifacthub/hub/releases/latest | grep -E 'browser_download_url' | grep linux_amd64 | grep -Eo 'https://[^\"]*' | xargs wget -O - | tar -xz
          for chart_dir in $CHARTS
          do
            ./ah lint -p $chart_dir || exit 1
          done
          rm -f ./ah

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@a3454e46a6f5ac4811069a381e646961dda2e1bf # tag=v1.4.0
        with:
          config: "./.github/configs/cr.yaml"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "{{ .Version }}-helm"